# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SeemsLegit.com
email: zach@lesriz.com
description: > # this means to ignore newlines until "baseurl:"
Seems Legit is a free to use website that provides an easy way to make your own website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seemslegit.com" # the base hostname & protocol for your site
github_username:  jefftheguyperson

# Build settings
markdown: kramdown
